spring.application.name=lab4

# === PostgreSQL ===
spring.datasource.url=jdbc:postgresql://localhost:5432/project_db
spring.datasource.username=project_user
spring.datasource.password=password

# === JPA / Hibernate ===
# 'create' ??????? ????? ??????? ?? ??????? ???? ??? ??????? ??????? (???????? ??????????? ??????)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# === ????????????? ????? ===
# ?????????? ????????????? ????? SQL-?????
spring.sql.init.mode=always
# ???????: ???????, ???? Hibernate ???????? ???????, ???? ??? ????????? INSERT
spring.jpa.defer-datasource-initialization=true
# ???????????? ??????, ???? ???? ??? ??????? (??? ???? ???????)
spring.sql.init.continue-on-error=true

# === Server ===
server.port=9090

# === CORS ===
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true